services:
  drupal:
    build: 
      context: . 
      dockerfile: Dockerfile
    container_name: drupal_app
    ports:
      - "8080:80"
    volumes:
      # - ./drupal_data:/var/www/html
      - drupal_data:/var/www/html
      - drupal_private:/var/www/private
    depends_on:
      - db
    environment:
      - PHP_MEMORY_LIMIT=2G

  db:
    image: mariadb:10.6
    container_name: drupal_db
    restart: always
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: drupal_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

volumes:
  drupal_data:
  drupal_private: